### ISSUE TITLE
Toolbar configuration in tinymce.yaml takes no effekt

### ISSUE THREAD

**Issue by kaistaerk** [eckinox/tinymce-bundle#16]
Hello,

i tried to configure my toolbar. If doing this in the FormType (attr -> toolbar), it works a bit, because I need the link plugin, but this seems not to be configured. So i switched to tinymce.yaml and check the values.
```
tinymce:
  # The configurations mirror the TinyMCE attributes.
  # Learn more about each option in Tiny's documentation:
  # https://www.tiny.cloud/docs/tinymce/6/webcomponent-ref/
  skin: "oxide"
  content_css: "default"
  plugins: "advlist autolink link image media table lists"
  toolbar: "bold italic underline link | bullist numlist"
```
No matter what I enter there, it shows no change.

Any idea's?

Thanks
Kai
